apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations: 
    argocd.argoproj.io/ignore-differences: |-
        jsonPointers:
        - /spec/
spec:
  replicas: 5
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: quay.io/argoprojlabs/argocd-e2e-container:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80

